#!/bin/bash
set -e

function remove_previous_forward {
  local pre_handles=($(nft list table nat -a | grep -e "dport[^}]\+27036[^}]\+} dnat" | awk -F# '{print $2}' | awk '{print $2}'))
  local post_handles=($(nft list table nat -a | grep -e "dport[^}]\+27036[^}]\+} snat" | awk -F# '{print $2}' | awk '{print $2}'))

  for handle in "${pre_handles[@]}"
  do
    nft delete rule nat PREROUTING handle ${handle}
  done
  for handle in "${post_handles[@]}"
  do
    nft delete rule nat POSTROUTING handle ${handle}
  done
}

function get_guest_ip {
  local guest=$1
  virsh domifaddr "${guest}" | tail -n2 | head -n1 | awk '{ print $4 }' | awk -F/ '{print $1}'
}

function add_forward {
  local guest_ip=$1

  nft add rule nat POSTROUTING ip saddr "${guest_ip}" udp dport { 27031-27036 } snat 192.168.9.10
  nft add rule nat POSTROUTING ip saddr "${guest_ip}" tcp dport { 27036-27037 } snat 192.168.9.10

  nft add rule nat PREROUTING ip daddr 192.168.9.10 udp dport { 27031-27036 } dnat "${guest_ip}"
  nft add rule nat PREROUTING ip daddr 192.168.9.10 tcp dport { 27036-27037 } dnat "${guest_ip}"

}

GUEST=$1
remove_previous_forward
IP=$(get_guest_ip $GUEST)
add_forward $IP
